Numpy : Practice Problem

1. Extract all odd numbers from arr


In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0]


array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [7]:
arr=np.arange(10)
arr.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [17]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >=5)& (a<=10)]


array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

7. Create a vector with values ranging from 10 to 49.

8. Create a 10x10 array with random values and find the minimum and maximum values.

9. Create a 3*3 matrix and print it's transpose matrix

10. Create two arrays of 2-D and find dot product of it.

11. Compute the maximum for each row in the given array.

In [18]:
#Q6 Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vector_1 = np.array([0,0,0,0,1,0,0,0,0,0])
vector_1.size

10

In [19]:
#Q7 Create a vector with values ranging from 10 to 49.
vector_2 = np.random.randint(10,50,(6,))
vector_2

array([37, 13, 24, 42, 17, 41])

In [22]:
#Q8 Create a 10x10 array with random values and find the minimum and maximum values.
matrix_1 = np.random.rand(10,10)
print('Matrix shape',matrix_1.shape)
print('Minimum value',matrix_1.min())
print('Maximum Value',matrix_1.max())

Matrix shape (10, 10)
Minimum value 0.0034393750153348668
Maximum Value 0.9991733358505205


In [28]:
#Q9 Create a 3*3 matrix and print it's transpose matrix
matrix_3 = np.random.randn(3,3)
print('Original Matrix')
print(matrix_3)
print('')
print('Matrix Shape',matrix_3.shape)
print('')
print('Transpose Of Matrix')
print(matrix_3.T)


Original Matrix
[[-0.02996563 -0.77663798  0.25570044]
 [ 0.95546195  1.19084845  0.35647506]
 [ 0.2182289  -1.33987735 -0.71773476]]

Matrix Shape (3, 3)

Transpose Of Matrix
[[-0.02996563  0.95546195  0.2182289 ]
 [-0.77663798  1.19084845 -1.33987735]
 [ 0.25570044  0.35647506 -0.71773476]]


In [30]:
#Q 10 Create two arrays of 2-D and find dot product of it. 
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[1,1,1],
                [2,2,2],
                [2,4,1]])
np.dot(arr1,arr2)

array([[11, 17,  8],
       [26, 38, 20]])

In [34]:
#Q11 Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
a.max(axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [43]:
data = np.random.randint(10,100,(5,4))
print(data)

[[24 43 30 50]
 [34 68 38 92]
 [92 17 12 73]
 [12 97 27 84]
 [63 40 77 38]]


In [44]:
data[[2,4],2:4]

array([[12, 73],
       [77, 38]])

13. Convert below matrix into vector

In [49]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [55]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)

print(m)
print('')
print(n)
print('')
print(np.dot(m,n))

[[2 3]
 [2 4]]

[[ 2.  -1.5]
 [-1.   1. ]]

[[1. 0.]
 [0. 1.]]


15. Create a matrix from a uniform distribution over [0, 1)

In [58]:
matrix = np.random.rand(2,2)
matrix

array([[0.3542983 , 0.50061432],
       [0.44517663, 0.09043279]])